### PR TITLE
Upgrade node engine version

### PR DESCRIPTION
**Pull request by rogaha**
- it fixes a vulnerability found recently (ref. https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/)

Signed-off-by: Roberto Gandolfo Hashioka <roberto_hashioka@hotmail.com>

### CODE REVIEW

**Comment by wilg** [comment]
Thanks! Was looking at this myself. We should also update `.nvmrc`.

**Comment by wilg** [comment]
I may need to close this and make a new PR to do that.

**Comment by wilg** [comment]
Thanks! Made the change in https://github.com/looker/lookerbot/commit/d9603e5b77bcd2e3e9d1f0de98be2d789c6c6237

**Comment by rogaha** [comment]
I could have done as well. np, thanks @wilg.

**Comment by wilg** [comment]
No problem @rogaha, just had some time to finish it up myself and didn't want to trouble you!

**Pull request closed without merging**
